app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

dashboard:
    resource: "@DashboardBundle/Controller/"
    type: annotation

character:
    resource: "@CharacterBundle/Controller/"
    type: annotation