parameters:
  silninuser.repository.class:              Silnin\BsgSheet\UserBundle\Entity\UserRepository
  silninuser.loginservice.class:            Silnin\BsgSheet\UserBundle\Service\LoginService
  silninuser.controller.class:              Silnin\BsgSheet\UserBundle\Controller\UserController
  silninuser.repository.factory_argument:   Silnin\BsgSheet\UserBundle\Entity\User

services:
  user.controller:
    class:            "%silninuser.controller.class%"

  user.repository:
    class:            "%silninuser.repository.class%"
    factory_service:  "doctrine.orm.entity_manager"
    factory_method:   "getRepository"
    arguments:
                - %silninuser.repository.factory_argument%



  user.login:
    class:            "%silninuser.loginservice.class%"
    arguments:
                - @user.repository
                - @doctrine.orm.entity_manager